### ISSUE TITLE
ModuleNotFoundError: No module named 'flask_bcrypt'

### ISSUE THREAD

**Issue by raveenb** [gothinkster/flask-realworld-example-app#31]
Hi,
I am getting this issue after following instructions on the page

----
  flask db init
Usage: flask db init [OPTIONS]

Error: While importing "autoapp", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/Users/raveenbeemsingh/Developer/conduit/flask-realworld-example-app/autoapp.py", line 5, in <module>
    from conduit.app import create_app
  File "/Users/raveenbeemsingh/Developer/conduit/flask-realworld-example-app/conduit/app.py", line 4, in <module>
    from conduit.extensions import bcrypt, cache, db, migrate, jwt, cors
  File "/Users/raveenbeemsingh/Developer/conduit/flask-realworld-example-app/conduit/extensions.py", line 4, in <module>
    from flask_bcrypt import Bcrypt
ModuleNotFoundError: No module named 'flask_bcrypt'

**Comment by limlynn** [comment]
try after this

pip install --upgrade setuptools 
sudo apt-get install libpq-dev python-dev
